/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "TSTS API Documentation",
  "tagline": "Complete API reference for the Technical Support Ticketing System",
  "favicon": "img/favicon.ico",
  "url": "http://localhost:8080",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "../docs",
          "routeBasePath": "/",
          "sidebarPath": "D:\\Personal_Data\\college\\Graduation_Project\\Resources\\versioning\\phase1\\code\\api\\docs-site\\sidebars.js",
          "breadcrumbs": true,
          "showLastUpdateTime": true
        },
        "blog": false,
        "theme": {
          "customCss": "D:\\Personal_Data\\college\\Graduation_Project\\Resources\\versioning\\phase1\\code\\api\\docs-site\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "TSTS API Docs",
      "logo": {
        "alt": "TSTS Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docs",
          "position": "left",
          "label": "Documentation"
        },
        {
          "href": "/",
          "label": "Back to App",
          "position": "right"
        },
        {
          "href": "https://openrouter.ai",
          "label": "Get Free AI Key",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Getting Started",
              "to": "/api-integrations"
            },
            {
              "label": "Authentication",
              "to": "/authentication/auth-v1"
            },
            {
              "label": "Tickets API",
              "to": "/tickets/tickets"
            }
          ]
        },
        {
          "title": "AI Assistant",
          "items": [
            {
              "label": "AI Assistant API",
              "to": "/management/ai-assistant"
            },
            {
              "label": "OpenRouter (Free AI)",
              "href": "https://openrouter.ai"
            },
            {
              "label": "Ollama (Local AI)",
              "href": "https://ollama.com"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 TSTS. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": []
      },
      "additionalLanguages": [
        "bash",
        "json",
        "typescript",
        "python"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
