// src/entities/index.ts
export * from "./User.js";
export * from "./TechnicianGroup.js";
export * from "./AllowedSpecialization.js";
export * from "./GroupHead.js";
export * from "./UsersPermissions.js";
export * from "./UserDepartment.js";
export * from "./University.js";
export * from "./Domain.js";
export * from "./Department.js";
export * from "./Group.js";
export * from "./GroupSpecialization.js";
export * from "./Specialization.js";
export * from "./WorkHour.js";
export * from "./Permission.js";
export * from "./PermissionProfile.js";
export * from "./KnowledgeItem.js";
export * from "./Media.js";
export * from "./Notification.js";
export * from "./NotificationRead.js";
export * from "./Ticket.js";
export * from "./TicketActivity.js";
export * from "./TicketChat.js";
export * from "./TicketListener.js";
export * from "./ChatMessage.js";
export * from "./TicketChatMessage.js";
export * from "./TrustedDevice.js";
export * from "./TicketReview.js";
export * from "./Problem.js"