version: "3.9"

services:
  api:
    container_name: api
    build:
      context: ../
      dockerfile: ./docker/DOCKERFILE
    restart: unless-stopped
    env_file:
      - ../.env
      
    ports:
      - "${PORT}:${PORT}"
    networks:
      - tsts-network
    volumes:
      - /opt/tsts-project/certs:/certs:ro

networks:
  tsts-network:
    external: true

