version: "3.9"

services:
  api:
    container_name: express_api
    build:
      context: ../
      dockerfile: ./docker/DOCKERFILE
    restart: unless-stopped
    env_file:
      - ../.env
      
    ports:
      - "${PORT}:${PORT}"
    networks:
      - tsts-network

networks:
  tsts-network:
    external: true

