# -------- 1. Build Stage --------
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build   # builds to dist/


# -------- 2. Production Stage --------
FROM node:20-alpine AS production
WORKDIR /app

# install PM2 globally
RUN npm install -g pm2

# Install only production dependencies
COPY package*.json ./
RUN npm install --omit=dev

# copy compiled JS only
COPY --from=builder /app/dist ./dist

USER node

EXPOSE 5000

CMD ["pm2-runtime", "dist/server.js"]
