import { MigrationInterface, QueryRunner } from "typeorm";

export class MainSchemaBaseline1768950396937 implements MigrationInterface {
    name = 'MainSchemaBaseline1768950396937'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const usersTableExists = await queryRunner.hasTable("users");
        if (usersTableExists) {
            console.log("[Migration] Main schema already exists, skipping baseline migration");
            return;
        }

        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "group_heads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "groupId" uuid, "userId" uuid, CONSTRAINT "PK_8fff563337f50bec7e39d039918" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "allowed_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "specializationId" uuid, CONSTRAINT "PK_6ac40e9fb00a80157bd6d0ddf5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "url" character varying NOT NULL, "mime" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ticketId" uuid, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_listeners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ticketId" uuid, "userId" uuid, CONSTRAINT "PK_ba4656836e5ee565ea77cda5167" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ticket_activities_type_enum" AS ENUM('out_of_service', 'info', 'error', 'closed', 'in_progress', 'assignee', 'resolved', 'pending', 'reopened', 'view', 'first_open', 'deleted')`);
        await queryRunner.query(`CREATE TABLE "ticket_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."ticket_activities_type_enum" NOT NULL, "title" character varying(150) NOT NULL, "content" text NOT NULL, "meta" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ticket_id" uuid, CONSTRAINT "PK_fea672ec7d9867e390d5a153881" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_chat" ("id" SERIAL NOT NULL, "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "senderId" uuid, "ticketId" uuid, CONSTRAINT "PK_a4493eeaf82350d370efbf479b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rating" integer NOT NULL, "note" text, "closeCycle" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "ticketId" uuid, "reviewerId" uuid NOT NULL, CONSTRAINT "PK_58c5859cb07ef043242fdfade11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14d8c643bc84d86143401d33f5" ON "ticket_reviews" ("ticketId", "closeCycle") `);
        await queryRunner.query(`CREATE TABLE "problems" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "description" jsonb, "review_required" boolean NOT NULL DEFAULT false, "specializationId" uuid NOT NULL, CONSTRAINT "PK_b3994afba6ab64a42cda1ccaeff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('open', 'in_progress', 'pending', 'closed', 'resolved', 're_open', 'out_of_service')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('important/urgent', 'important', 'urgent', 'NA')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(100) NOT NULL, "description" text NOT NULL, "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'open', "priority" "public"."tickets_priority_enum" NOT NULL DEFAULT 'NA', "isOutOfService" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "modifiedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "closeCount" integer NOT NULL DEFAULT '0', "requesterId" uuid NOT NULL, "specializationId" uuid, "problemId" uuid, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "description" jsonb, "review_required" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_1d4b2b9ff96a76def0bf7195a8f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "group_specializations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "groupId" uuid, "specializationId" uuid, CONSTRAINT "PK_c1024eb3508634b6ef0f4ce08d4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "senderId" uuid, "groupId" uuid, "recipientId" uuid, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb, "descriptions" jsonb, "color" character varying(255), "teamLeaderId" uuid, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "technician_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "groupId" uuid, CONSTRAINT "PK_d8230a24f6e6cb3417dc077e3fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permission_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "descriptions" jsonb, CONSTRAINT "PK_c18c284fe081d6be0a19aecd188" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "key" character varying(20), "name" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions" ("key") `);
        await queryRunner.query(`CREATE TABLE "users_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "permissionProfileId" uuid, CONSTRAINT "PK_24cf766157134356eca5db6395a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "universities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "description" jsonb, CONSTRAINT "PK_8da52f2cee6b407559fdbabf59e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "domains" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "description" jsonb, "universityId" uuid, CONSTRAINT "PK_05a6b087662191c2ea7f7ddfc4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" jsonb NOT NULL, "description" jsonb, "domainId" uuid, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_departments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "departmentId" uuid, CONSTRAINT "PK_ca8d1bbbf9bb49c79c706807fae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('system', 'ticket', 'message', 'other')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notifications_type_enum" NOT NULL, "title" text NOT NULL, "content" text, "ticketId" uuid, "chatMessageId" uuid, "extraReference" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification_reads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "notificationId" uuid, "userId" uuid, CONSTRAINT "PK_c49ec541db45925cfb4e5c8dfbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trusted_devices_devicetype_enum" AS ENUM('desktop', 'mobile', 'tablet')`);
        await queryRunner.query(`CREATE TABLE "trusted_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "deviceType" "public"."trusted_devices_devicetype_enum" NOT NULL, "browser" character varying NOT NULL, "os" character varying NOT NULL, "credentialId" character varying NOT NULL, "publicKey" bytea NOT NULL, "counter" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "activatedSince" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "ipAddress" character varying NOT NULL, "userId" uuid, CONSTRAINT "UQ_db8f0b05eda112b49f13977ada7" UNIQUE ("credentialId"), CONSTRAINT "PK_bc545fd72c357ff2edc8bbc7deb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_69087bb54304653221daadcd27" ON "trusted_devices" ("userId", "credentialId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_user_type_enum" AS ENUM('Requester', 'Admin', 'Technician', 'SuperAdmin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "image" character varying(500), "firstName" jsonb, "midName" jsonb, "lastName" jsonb, "fullName" jsonb, "ssn" character varying(14), "user_type" "public"."users_user_type_enum", "contacts" jsonb, "refreshToken" character varying(255), "status" "public"."users_status_enum" NOT NULL DEFAULT 'Inactive', "job" jsonb, "universityId" uuid, "domainId" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_USER_SSN" ON "users" ("ssn") `);
        await queryRunner.query(`CREATE TYPE "public"."work_hours_status_enum" AS ENUM('Active', 'Inactive')`);
        await queryRunner.query(`CREATE TYPE "public"."work_hours_day_enum" AS ENUM('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')`);
        await queryRunner.query(`CREATE TABLE "work_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "status" "public"."work_hours_status_enum" NOT NULL DEFAULT 'Active', "day" "public"."work_hours_day_enum" NOT NULL, CONSTRAINT "PK_db68f0fe2457d44e728b89458df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "knowledge_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "title" character varying(255) NOT NULL, "description" character varying(1000) NOT NULL, "specialization" character varying(100) NOT NULL, "content" character varying(200000), "search_vector" tsvector, CONSTRAINT "PK_4da6043fefe372aa8151664e3b2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff1e05ac110889fce82ed2897c" ON "knowledge_items" ("specialization") `);
        await queryRunner.query(`CREATE TABLE "ticket_chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "senderId" uuid, "ticketId" uuid, CONSTRAINT "PK_9a7488f627c81195d1ea5ccbd32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "handler" character varying NOT NULL, "title" jsonb NOT NULL, "description" jsonb, "search_vector" tsvector, "columns" jsonb, "filters" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_08290a42004f1fcb69a4d28311e" UNIQUE ("handler"), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08290a42004f1fcb69a4d28311" ON "reports" ("handler") `);
        await queryRunner.query(`CREATE TABLE "ticket_assignees" ("ticket_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_49d04304a7c7688219e6f5e68a0" PRIMARY KEY ("ticket_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b36b35959597de6ae8bf2b43ca" ON "ticket_assignees" ("ticket_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c653a891aa11e08c1382b1f80f" ON "ticket_assignees" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "chat_message_media" ("chatMessagesId" uuid NOT NULL, "mediaId" uuid NOT NULL, CONSTRAINT "PK_26f1b189317f71dc03c344ad817" PRIMARY KEY ("chatMessagesId", "mediaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c74984bd0dbd142baa13dfa5c5" ON "chat_message_media" ("chatMessagesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_300a822ae4b60c79b70b2974c8" ON "chat_message_media" ("mediaId") `);
        await queryRunner.query(`CREATE TABLE "permission_profile_permissions" ("permissionProfileId" uuid NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_9d3071049784d7569d22551d0d6" PRIMARY KEY ("permissionProfileId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3522919553c383be1933e5e4f1" ON "permission_profile_permissions" ("permissionProfileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d768b9b4d4cfe538d2ab688c58" ON "permission_profile_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "users_activated_permissions" ("usersPermissionsId" uuid NOT NULL, "permissionsId" integer NOT NULL, CONSTRAINT "PK_2879fd3e7d788aff6ac1e42fa30" PRIMARY KEY ("usersPermissionsId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb77c23652644bc71f9206cc9a" ON "users_activated_permissions" ("usersPermissionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6734c332ae654f6ddb1a614159" ON "users_activated_permissions" ("permissionsId") `);
        await queryRunner.query(`CREATE TABLE "users_permissions_extra" ("usersPermissionsId" uuid NOT NULL, "permissionsId" integer NOT NULL, CONSTRAINT "PK_d533e33487e710f9710277b3c71" PRIMARY KEY ("usersPermissionsId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7cd9c3da72840ecafb80fd67c" ON "users_permissions_extra" ("usersPermissionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9aade6439e2ce9d44419de235" ON "users_permissions_extra" ("permissionsId") `);
        await queryRunner.query(`CREATE TABLE "users_permissions_revoked" ("usersPermissionsId" uuid NOT NULL, "permissionsId" integer NOT NULL, CONSTRAINT "PK_52f182534a0d985a060fa2a06fb" PRIMARY KEY ("usersPermissionsId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1c542e441251ec39d94bf773a" ON "users_permissions_revoked" ("usersPermissionsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_956070d51dc1c36e6063ee8254" ON "users_permissions_revoked" ("permissionsId") `);
        await queryRunner.query(`CREATE TABLE "ticket_chat_message_media" ("ticketChatMessagesId" uuid NOT NULL, "mediaId" uuid NOT NULL, CONSTRAINT "PK_48b8a339f35e9165056f68742f7" PRIMARY KEY ("ticketChatMessagesId", "mediaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41b4c6c01b3285b192179d0b8c" ON "ticket_chat_message_media" ("ticketChatMessagesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_07f410de4985b1c9a5d18afb65" ON "ticket_chat_message_media" ("mediaId") `);
        await queryRunner.query(`ALTER TABLE "group_heads" ADD CONSTRAINT "FK_539f0841974ac89d6679625364c" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_heads" ADD CONSTRAINT "FK_58105fa938e4010ecb92e6fb5a7" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allowed_specializations" ADD CONSTRAINT "FK_f52332f7f5d6b43960c7fadfaa9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "allowed_specializations" ADD CONSTRAINT "FK_aaff5bc8869115a013e6668698c" FOREIGN KEY ("specializationId") REFERENCES "specializations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media" ADD CONSTRAINT "FK_792a1158283757c3ad63cde3ee9" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_listeners" ADD CONSTRAINT "FK_6950582466f2bd997186a4d07a0" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_listeners" ADD CONSTRAINT "FK_22d1f13f98b3ba87ff0a38635ba" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_activities" ADD CONSTRAINT "FK_2715f926ba0ddd73514eb0bef61" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_chat" ADD CONSTRAINT "FK_fb6096ab7ca3ca775df645777ef" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_chat" ADD CONSTRAINT "FK_08b780f8247574b1dca40253b84" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_reviews" ADD CONSTRAINT "FK_60b61fb133956075cb76e690ef7" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_reviews" ADD CONSTRAINT "FK_c31b9655ca3809311ceabe96997" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "problems" ADD CONSTRAINT "FK_39b923392e27eb43190d44b6793" FOREIGN KEY ("specializationId") REFERENCES "specializations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ffff1b4554585c0c9b95d062605" FOREIGN KEY ("requesterId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_901f92d4c5e5076b8ddc717148f" FOREIGN KEY ("specializationId") REFERENCES "specializations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_ee31e7007107052dbb79066cafe" FOREIGN KEY ("problemId") REFERENCES "problems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_specializations" ADD CONSTRAINT "FK_82d7f866cde4d0aee5448f063c5" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_specializations" ADD CONSTRAINT "FK_7377eeeb24149f7ead2ad369fb6" FOREIGN KEY ("specializationId") REFERENCES "specializations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_a1a0a3530904943e6ff731aeb32" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_7be9cbcf5322849a63d6faf9c6a" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_f4ede9c44e42cf9dc6c90d7430a" FOREIGN KEY ("teamLeaderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technician_groups" ADD CONSTRAINT "FK_aa68ccea5c6538661c3c797c651" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technician_groups" ADD CONSTRAINT "FK_8dfe88a26504d12e56064ff3903" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_permissions" ADD CONSTRAINT "FK_4180c1a3fdc77c74e9ad3a387f2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_permissions" ADD CONSTRAINT "FK_7dad15f1afe4e13e2ff695d32bd" FOREIGN KEY ("permissionProfileId") REFERENCES "permission_profile"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "domains" ADD CONSTRAINT "FK_12465e3e9ac4ae47bc24d69a5a9" FOREIGN KEY ("universityId") REFERENCES "universities"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_b255f1a1c4f808495731978d1ea" FOREIGN KEY ("domainId") REFERENCES "domains"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_departments" ADD CONSTRAINT "FK_b6a6b84016474c21464a8a47ebd" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_departments" ADD CONSTRAINT "FK_4233307a4905e7f1b252d1b009e" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_38d077b9c1f597ae662c5ae4119" FOREIGN KEY ("notificationId") REFERENCES "notifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_reads" ADD CONSTRAINT "FK_bddd24aed9c7f0beee6e8d8339f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trusted_devices" ADD CONSTRAINT "FK_d1623ce96eb58dbfc177e00e413" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_8d6cca8bed5c786796851b759aa" FOREIGN KEY ("universityId") REFERENCES "universities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_66c4d25f791114c430837b75a2e" FOREIGN KEY ("domainId") REFERENCES "domains"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_messages" ADD CONSTRAINT "FK_7b0f3f0566bfc1227ebd16dabd6" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_messages" ADD CONSTRAINT "FK_6b0d00b2898bd31513854bb2ecd" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_b36b35959597de6ae8bf2b43ca6" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" ADD CONSTRAINT "FK_c653a891aa11e08c1382b1f80f3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "chat_message_media" ADD CONSTRAINT "FK_c74984bd0dbd142baa13dfa5c52" FOREIGN KEY ("chatMessagesId") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "chat_message_media" ADD CONSTRAINT "FK_300a822ae4b60c79b70b2974c86" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "permission_profile_permissions" ADD CONSTRAINT "FK_3522919553c383be1933e5e4f1a" FOREIGN KEY ("permissionProfileId") REFERENCES "permission_profile"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "permission_profile_permissions" ADD CONSTRAINT "FK_d768b9b4d4cfe538d2ab688c58e" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_activated_permissions" ADD CONSTRAINT "FK_cb77c23652644bc71f9206cc9ac" FOREIGN KEY ("usersPermissionsId") REFERENCES "users_permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_activated_permissions" ADD CONSTRAINT "FK_6734c332ae654f6ddb1a6141596" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_permissions_extra" ADD CONSTRAINT "FK_f7cd9c3da72840ecafb80fd67cc" FOREIGN KEY ("usersPermissionsId") REFERENCES "users_permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_permissions_extra" ADD CONSTRAINT "FK_a9aade6439e2ce9d44419de235f" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_permissions_revoked" ADD CONSTRAINT "FK_b1c542e441251ec39d94bf773a6" FOREIGN KEY ("usersPermissionsId") REFERENCES "users_permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_permissions_revoked" ADD CONSTRAINT "FK_956070d51dc1c36e6063ee82545" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_message_media" ADD CONSTRAINT "FK_41b4c6c01b3285b192179d0b8c6" FOREIGN KEY ("ticketChatMessagesId") REFERENCES "ticket_chat_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_message_media" ADD CONSTRAINT "FK_07f410de4985b1c9a5d18afb650" FOREIGN KEY ("mediaId") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const usersTableExists = await queryRunner.hasTable("users");
        if (!usersTableExists) {
            return;
        }

        await queryRunner.query(`ALTER TABLE "ticket_chat_message_media" DROP CONSTRAINT "FK_07f410de4985b1c9a5d18afb650"`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_message_media" DROP CONSTRAINT "FK_41b4c6c01b3285b192179d0b8c6"`);
        await queryRunner.query(`ALTER TABLE "users_permissions_revoked" DROP CONSTRAINT "FK_956070d51dc1c36e6063ee82545"`);
        await queryRunner.query(`ALTER TABLE "users_permissions_revoked" DROP CONSTRAINT "FK_b1c542e441251ec39d94bf773a6"`);
        await queryRunner.query(`ALTER TABLE "users_permissions_extra" DROP CONSTRAINT "FK_a9aade6439e2ce9d44419de235f"`);
        await queryRunner.query(`ALTER TABLE "users_permissions_extra" DROP CONSTRAINT "FK_f7cd9c3da72840ecafb80fd67cc"`);
        await queryRunner.query(`ALTER TABLE "users_activated_permissions" DROP CONSTRAINT "FK_6734c332ae654f6ddb1a6141596"`);
        await queryRunner.query(`ALTER TABLE "users_activated_permissions" DROP CONSTRAINT "FK_cb77c23652644bc71f9206cc9ac"`);
        await queryRunner.query(`ALTER TABLE "permission_profile_permissions" DROP CONSTRAINT "FK_d768b9b4d4cfe538d2ab688c58e"`);
        await queryRunner.query(`ALTER TABLE "permission_profile_permissions" DROP CONSTRAINT "FK_3522919553c383be1933e5e4f1a"`);
        await queryRunner.query(`ALTER TABLE "chat_message_media" DROP CONSTRAINT "FK_300a822ae4b60c79b70b2974c86"`);
        await queryRunner.query(`ALTER TABLE "chat_message_media" DROP CONSTRAINT "FK_c74984bd0dbd142baa13dfa5c52"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_c653a891aa11e08c1382b1f80f3"`);
        await queryRunner.query(`ALTER TABLE "ticket_assignees" DROP CONSTRAINT "FK_b36b35959597de6ae8bf2b43ca6"`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_messages" DROP CONSTRAINT "FK_6b0d00b2898bd31513854bb2ecd"`);
        await queryRunner.query(`ALTER TABLE "ticket_chat_messages" DROP CONSTRAINT "FK_7b0f3f0566bfc1227ebd16dabd6"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_66c4d25f791114c430837b75a2e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_8d6cca8bed5c786796851b759aa"`);
        await queryRunner.query(`ALTER TABLE "trusted_devices" DROP CONSTRAINT "FK_d1623ce96eb58dbfc177e00e413"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_bddd24aed9c7f0beee6e8d8339f"`);
        await queryRunner.query(`ALTER TABLE "notification_reads" DROP CONSTRAINT "FK_38d077b9c1f597ae662c5ae4119"`);
        await queryRunner.query(`ALTER TABLE "user_departments" DROP CONSTRAINT "FK_4233307a4905e7f1b252d1b009e"`);
        await queryRunner.query(`ALTER TABLE "user_departments" DROP CONSTRAINT "FK_b6a6b84016474c21464a8a47ebd"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_b255f1a1c4f808495731978d1ea"`);
        await queryRunner.query(`ALTER TABLE "domains" DROP CONSTRAINT "FK_12465e3e9ac4ae47bc24d69a5a9"`);
        await queryRunner.query(`ALTER TABLE "users_permissions" DROP CONSTRAINT "FK_7dad15f1afe4e13e2ff695d32bd"`);
        await queryRunner.query(`ALTER TABLE "users_permissions" DROP CONSTRAINT "FK_4180c1a3fdc77c74e9ad3a387f2"`);
        await queryRunner.query(`ALTER TABLE "technician_groups" DROP CONSTRAINT "FK_8dfe88a26504d12e56064ff3903"`);
        await queryRunner.query(`ALTER TABLE "technician_groups" DROP CONSTRAINT "FK_aa68ccea5c6538661c3c797c651"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_f4ede9c44e42cf9dc6c90d7430a"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_7be9cbcf5322849a63d6faf9c6a"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_a1a0a3530904943e6ff731aeb32"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_fc6b58e41e9a871dacbe9077def"`);
        await queryRunner.query(`ALTER TABLE "group_specializations" DROP CONSTRAINT "FK_7377eeeb24149f7ead2ad369fb6"`);
        await queryRunner.query(`ALTER TABLE "group_specializations" DROP CONSTRAINT "FK_82d7f866cde4d0aee5448f063c5"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ee31e7007107052dbb79066cafe"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_901f92d4c5e5076b8ddc717148f"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_ffff1b4554585c0c9b95d062605"`);
        await queryRunner.query(`ALTER TABLE "problems" DROP CONSTRAINT "FK_39b923392e27eb43190d44b6793"`);
        await queryRunner.query(`ALTER TABLE "ticket_reviews" DROP CONSTRAINT "FK_c31b9655ca3809311ceabe96997"`);
        await queryRunner.query(`ALTER TABLE "ticket_reviews" DROP CONSTRAINT "FK_60b61fb133956075cb76e690ef7"`);
        await queryRunner.query(`ALTER TABLE "ticket_chat" DROP CONSTRAINT "FK_08b780f8247574b1dca40253b84"`);
        await queryRunner.query(`ALTER TABLE "ticket_chat" DROP CONSTRAINT "FK_fb6096ab7ca3ca775df645777ef"`);
        await queryRunner.query(`ALTER TABLE "ticket_activities" DROP CONSTRAINT "FK_2715f926ba0ddd73514eb0bef61"`);
        await queryRunner.query(`ALTER TABLE "ticket_listeners" DROP CONSTRAINT "FK_22d1f13f98b3ba87ff0a38635ba"`);
        await queryRunner.query(`ALTER TABLE "ticket_listeners" DROP CONSTRAINT "FK_6950582466f2bd997186a4d07a0"`);
        await queryRunner.query(`ALTER TABLE "media" DROP CONSTRAINT "FK_792a1158283757c3ad63cde3ee9"`);
        await queryRunner.query(`ALTER TABLE "allowed_specializations" DROP CONSTRAINT "FK_aaff5bc8869115a013e6668698c"`);
        await queryRunner.query(`ALTER TABLE "allowed_specializations" DROP CONSTRAINT "FK_f52332f7f5d6b43960c7fadfaa9"`);
        await queryRunner.query(`ALTER TABLE "group_heads" DROP CONSTRAINT "FK_58105fa938e4010ecb92e6fb5a7"`);
        await queryRunner.query(`ALTER TABLE "group_heads" DROP CONSTRAINT "FK_539f0841974ac89d6679625364c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07f410de4985b1c9a5d18afb65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41b4c6c01b3285b192179d0b8c"`);
        await queryRunner.query(`DROP TABLE "ticket_chat_message_media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_956070d51dc1c36e6063ee8254"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1c542e441251ec39d94bf773a"`);
        await queryRunner.query(`DROP TABLE "users_permissions_revoked"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9aade6439e2ce9d44419de235"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7cd9c3da72840ecafb80fd67c"`);
        await queryRunner.query(`DROP TABLE "users_permissions_extra"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6734c332ae654f6ddb1a614159"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb77c23652644bc71f9206cc9a"`);
        await queryRunner.query(`DROP TABLE "users_activated_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d768b9b4d4cfe538d2ab688c58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3522919553c383be1933e5e4f1"`);
        await queryRunner.query(`DROP TABLE "permission_profile_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_300a822ae4b60c79b70b2974c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74984bd0dbd142baa13dfa5c5"`);
        await queryRunner.query(`DROP TABLE "chat_message_media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c653a891aa11e08c1382b1f80f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36b35959597de6ae8bf2b43ca"`);
        await queryRunner.query(`DROP TABLE "ticket_assignees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08290a42004f1fcb69a4d28311"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "ticket_chat_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff1e05ac110889fce82ed2897c"`);
        await queryRunner.query(`DROP TABLE "knowledge_items"`);
        await queryRunner.query(`DROP TABLE "work_hours"`);
        await queryRunner.query(`DROP TYPE "public"."work_hours_day_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_hours_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_USER_SSN"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_user_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69087bb54304653221daadcd27"`);
        await queryRunner.query(`DROP TABLE "trusted_devices"`);
        await queryRunner.query(`DROP TYPE "public"."trusted_devices_devicetype_enum"`);
        await queryRunner.query(`DROP TABLE "notification_reads"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_departments"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "domains"`);
        await queryRunner.query(`DROP TABLE "universities"`);
        await queryRunner.query(`DROP TABLE "users_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "permission_profile"`);
        await queryRunner.query(`DROP TABLE "technician_groups"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TABLE "group_specializations"`);
        await queryRunner.query(`DROP TABLE "specializations"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TABLE "problems"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14d8c643bc84d86143401d33f5"`);
        await queryRunner.query(`DROP TABLE "ticket_reviews"`);
        await queryRunner.query(`DROP TABLE "ticket_chat"`);
        await queryRunner.query(`DROP TABLE "ticket_activities"`);
        await queryRunner.query(`DROP TYPE "public"."ticket_activities_type_enum"`);
        await queryRunner.query(`DROP TABLE "ticket_listeners"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TABLE "allowed_specializations"`);
        await queryRunner.query(`DROP TABLE "group_heads"`);
    }

}
